/*
 * Ntsnaf_BridgeInfoManagement Service API
 *
 * The Ntsnaf_BridgeInfoManagement Service is used by TSNAF and CNC to communicate with bridge Information container
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Ntsnaf_BridgeInfoManagement

// APIClient manages communication with the Npcf_PolicyAuthorization Service API API v1.0.1
// In most cases there should be only one, shared, APIClient.
type APIClient struct {
	cfg    *Configuration
	common service // Reuse a single struct instead of allocating one for each service on the heap.

	// API Services
	BridgeInfoManagementBridgeInformationRegistrationApi *BridgeInfoManagementBridgeInformationRegistrationApiService
}

type service struct {
	client *APIClient
}

func NewAPIClient(cfg *Configuration) *APIClient {
	c := &APIClient{}
	c.cfg = cfg
	c.common.client = c

	// API Services
	c.BridgeInfoManagementBridgeInformationRegistrationApi = (*BridgeInfoManagementBridgeInformationRegistrationApiService)(&c.common)

	return c
}
