/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Contains configuration for each port.
type ConfigForPort struct {
	// String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause  2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \"imsi-<imsi>\", where <imsi> shall be formatted according to clause 2.2    of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \"nai-<nai>, where <nai> shall be formatted    according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \"gci-<gci>\", where <gci> shall be formatted according to clause 28.15.2    of 3GPP TS 23.003.  - for a GLI \"gli-<gli>\", where <gli> shall be formatted according to clause 28.16.2 of    3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall    only contain characters allowed according to the \"lower-with-hyphen\" naming convention    defined in 3GPP TS 29.501.
	Supi string `json:"supi,omitempty" yaml:"supi" bson:"supi" mapstructure:"Supi"`
	// String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-'extid', where 'extid'  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.
	Gpsi             string `json:"gpsi,omitempty" yaml:"gpsi" bson:"gpsi" mapstructure:"Gpsi"`
	N6Ind            bool   `json:"n6Ind,omitempty" yaml:"n6Ind" bson:"n6Ind" mapstructure:"N6Ind"`
	PtpEnable        bool   `json:"ptpEnable,omitempty" yaml:"ptpEnable" bson:"ptpEnable" mapstructure:"PtpEnable"`
	LogSyncInter     int32  `json:"logSyncInter,omitempty" yaml:"logSyncInter" bson:"logSyncInter" mapstructure:"LogSyncInter"`
	LogSyncInterInd  bool   `json:"logSyncInterInd,omitempty" yaml:"logSyncInterInd" bson:"logSyncInterInd" mapstructure:"LogSyncInterInd"`
	LogAnnouInter    int32  `json:"logAnnouInter,omitempty" yaml:"logAnnouInter" bson:"logAnnouInter" mapstructure:"LogAnnouInter"`
	LogAnnouInterInd bool   `json:"logAnnouInterInd,omitempty" yaml:"logAnnouInterInd" bson:"logAnnouInterInd" mapstructure:"LogAnnouInterInd"`
}
