/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Contains the notification of time synchronization service state.
type TimeSyncExposureConfigNotif struct {
	// Notification Correlation ID assigned by the NF service consumer.
	ConfigNotifId string `json:"configNotifId" yaml:"configNotifId" bson:"configNotifId" mapstructure:"ConfigNotifId"`
	StateOfConfig *StateOfConfiguration `json:"stateOfConfig" yaml:"stateOfConfig" bson:"stateOfConfig" mapstructure:"StateOfConfig"`
}
