/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.2.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type NfType string

// List of NFType
const (
	NfType_NRF        NfType = "NRF"
	NfType_UDM        NfType = "UDM"
	NfType_AMF        NfType = "AMF"
	NfType_SMF        NfType = "SMF"
	NfType_AUSF       NfType = "AUSF"
	NfType_NEF        NfType = "NEF"
	NfType_PCF        NfType = "PCF"
	NfType_SMSF       NfType = "SMSF"
	NfType_NSSF       NfType = "NSSF"
	NfType_UDR        NfType = "UDR"
	NfType_LMF        NfType = "LMF"
	NfType_GMLC       NfType = "GMLC"
	NfType__5_G_EIR   NfType = "5G_EIR"
	NfType_SEPP       NfType = "SEPP"
	NfType_UPF        NfType = "UPF"
	NfType_N3_IWF     NfType = "N3IWF"
	NfType_AF         NfType = "AF"
	NfType_UDSF       NfType = "UDSF"
	NfType_BSF        NfType = "BSF"
	NfType_CHF        NfType = "CHF"
	NfType_NWDAF      NfType = "NWDAF"
	NfType_PCSCF      NfType = "PCSCF"
	NfType_CBCF       NfType = "CBCF"
	NfType_HSS        NfType = "HSS"
	NfType_UCMF       NfType = "UCMF"
	NfType_SOR_AF     NfType = "SOR_AF"
	NfType_SPAF       NfType = "SPAF"
	NfType_MME        NfType = "MME"
	NfType_SCSAS      NfType = "SCSAS"
	NfType_SCEF       NfType = "SCEF"
	NfType_SCP        NfType = "SCP"
	NfType_NSSAAF     NfType = "NSSAAF"
	NfType_ICSCF      NfType = "ICSCF"
	NfType_SCSCF      NfType = "SCSCF"
	NfType_DRA        NfType = "DRA"
	NfType_IMS_AS     NfType = "IMS_AS"
	NfType_AANF       NfType = "AANF"
	NfType__5_G_DDNMF NfType = "5G_DDNMF"
	NfType_NSACF      NfType = "NSACF"
	NfType_MFAF       NfType = "MFAF"
	NfType_EASDF      NfType = "EASDF"
	NfType_DCCF       NfType = "DCCF"
	NfType_MB_SMF     NfType = "MB_SMF"
	NfType_TSCTSF     NfType = "TSCTSF"
	NfType_ADRF       NfType = "ADRF"
	NfType_GBA_BSF    NfType = "GBA_BSF"
	NfType_CEF        NfType = "CEF"
	NfType_MB_UPF     NfType = "MB_UPF"
	NfType_NSWOF      NfType = "NSWOF"
	NfType_PKMF       NfType = "PKMF"
	NfType_MNPF       NfType = "MNPF"
	NfType_SMS_GMSC   NfType = "SMS_GMSC"
	NfType_SMS_IWMSC  NfType = "SMS_IWMSC"
	NfType_MBSF       NfType = "MBSF"
	NfType_MBSTF      NfType = "MBSTF"
	NfType_PANF       NfType = "PANF"
)
