/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type InstanceType string

// List of InstanceType
const (
	InstanceType_BOUNDARY_CLOCK      InstanceType = "BOUNDARY_CLOCK"
	InstanceType_E2_E_TRANS_CLOCK    InstanceType = "E2E_TRANS_CLOCK"
	InstanceType_P2_P_TRANS_CLOCK    InstanceType = "P2P_TRANS_CLOCK"
	InstanceType_P2_P_RELAY_INSTANCE InstanceType = "P2P_RELAY_INSTANCE"
)
