/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models
type Protocol string

// List of Protocol
const (
	Protocol_ETH Protocol = "ETH"
	Protocol_IPV4 Protocol = "IPV4"
	Protocol_IPV6 Protocol = "IPV6"
)